module Emoji exposing (Emoji, Emojis, emojis, toList, search)

import Dict exposing (Dict)


type alias Emoji =
    ( String, List String )


type alias Emojis =
    Dict String Emoji


toList : Emojis -> List ( String, Emoji )
toList =
    Dict.toList


search : String -> Emojis -> Emojis
search prefix emojis =
    Dict.filter (\_ ( _, strings ) -> List.any (\s -> String.contains prefix s) strings) emojis


emojis : Emojis
emojis =
    Dict.empty
        |> Dict.insert "00a9" ( "©", [ "copyright" ] )
        |> Dict.insert "00ae" ( "®", [ "registered" ] )
        |> Dict.insert "203c" ( "‼", [ "bangbang" ] )
        |> Dict.insert "2049" ( "⁉", [ "interrobang" ] )
        |> Dict.insert "2122" ( "™", [ "tm" ] )
        |> Dict.insert "2139" ( "ℹ", [ "information_source" ] )
        |> Dict.insert "2194" ( "↔", [ "left_right_arrow" ] )
        |> Dict.insert "2195" ( "↕", [ "arrow_up_down" ] )
        |> Dict.insert "2196" ( "↖", [ "arrow_upper_left" ] )
        |> Dict.insert "2197" ( "↗", [ "arrow_upper_right" ] )
        |> Dict.insert "2198" ( "↘", [ "arrow_lower_right" ] )
        |> Dict.insert "2199" ( "↙", [ "arrow_lower_left" ] )
        |> Dict.insert "21a9" ( "↩", [ "leftwards_arrow_with_hook" ] )
        |> Dict.insert "21aa" ( "↪", [ "arrow_right_hook" ] )
        |> Dict.insert "231a" ( "⌚", [ "watch" ] )
        |> Dict.insert "231b" ( "⌛", [ "hourglass" ] )
        |> Dict.insert "23e9" ( "⏩", [ "fast_forward" ] )
        |> Dict.insert "23ea" ( "⏪", [ "rewind" ] )
        |> Dict.insert "23eb" ( "⏫", [ "arrow_double_up" ] )
        |> Dict.insert "23ec" ( "⏬", [ "arrow_double_down" ] )
        |> Dict.insert "23f0" ( "⏰", [ "alarm_clock" ] )
        |> Dict.insert "23f3" ( "⏳", [ "hourglass_flowing_sand" ] )
        |> Dict.insert "24c2" ( "Ⓜ", [ "m" ] )
        |> Dict.insert "25aa" ( "▪", [ "black_small_square" ] )
        |> Dict.insert "25ab" ( "▫", [ "white_small_square" ] )
        |> Dict.insert "25b6" ( "▶", [ "arrow_forward" ] )
        |> Dict.insert "25c0" ( "◀", [ "arrow_backward" ] )
        |> Dict.insert "25fb" ( "◻", [ "white_medium_square" ] )
        |> Dict.insert "25fc" ( "◼", [ "black_medium_square" ] )
        |> Dict.insert "25fd" ( "◽", [ "white_medium_small_square" ] )
        |> Dict.insert "25fe" ( "◾", [ "black_medium_small_square" ] )
        |> Dict.insert "2600" ( "☀", [ "sunny" ] )
        |> Dict.insert "2601" ( "☁", [ "cloud" ] )
        |> Dict.insert "260e" ( "☎", [ "phone", "telephone" ] )
        |> Dict.insert "2611" ( "☑", [ "ballot_box_with_check" ] )
        |> Dict.insert "2614" ( "☔", [ "umbrella" ] )
        |> Dict.insert "2615" ( "☕", [ "coffee" ] )
        |> Dict.insert "261d" ( "☝", [ "point_up" ] )
        |> Dict.insert "263a" ( "☺", [ "relaxed" ] )
        |> Dict.insert "2648" ( "♈", [ "aries" ] )
        |> Dict.insert "2649" ( "♉", [ "taurus" ] )
        |> Dict.insert "264a" ( "♊", [ "gemini" ] )
        |> Dict.insert "264b" ( "♋", [ "cancer" ] )
        |> Dict.insert "264c" ( "♌", [ "leo" ] )
        |> Dict.insert "264d" ( "♍", [ "virgo" ] )
        |> Dict.insert "264e" ( "♎", [ "libra" ] )
        |> Dict.insert "264f" ( "♏", [ "scorpius" ] )
        |> Dict.insert "2650" ( "♐", [ "sagittarius" ] )
        |> Dict.insert "2651" ( "♑", [ "capricorn" ] )
        |> Dict.insert "2652" ( "♒", [ "aquarius" ] )
        |> Dict.insert "2653" ( "♓", [ "pisces" ] )
        |> Dict.insert "2660" ( "♠", [ "spades" ] )
        |> Dict.insert "2663" ( "♣", [ "clubs" ] )
        |> Dict.insert "2665" ( "♥", [ "hearts" ] )
        |> Dict.insert "2666" ( "♦", [ "diamonds" ] )
        |> Dict.insert "2668" ( "♨", [ "hotsprings" ] )
        |> Dict.insert "267b" ( "♻", [ "recycle" ] )
        |> Dict.insert "267f" ( "♿", [ "wheelchair" ] )
        |> Dict.insert "2693" ( "⚓", [ "anchor" ] )
        |> Dict.insert "26a0" ( "⚠", [ "warning" ] )
        |> Dict.insert "26a1" ( "⚡", [ "zap" ] )
        |> Dict.insert "26aa" ( "⚪", [ "white_circle" ] )
        |> Dict.insert "26ab" ( "⚫", [ "black_circle" ] )
        |> Dict.insert "26bd" ( "⚽", [ "soccer" ] )
        |> Dict.insert "26be" ( "⚾", [ "baseball" ] )
        |> Dict.insert "26c4" ( "⛄", [ "snowman" ] )
        |> Dict.insert "26c5" ( "⛅", [ "partly_sunny" ] )
        |> Dict.insert "26ce" ( "⛎", [ "ophiuchus" ] )
        |> Dict.insert "26d4" ( "⛔", [ "no_entry" ] )
        |> Dict.insert "26ea" ( "⛪", [ "church" ] )
        |> Dict.insert "26f2" ( "⛲", [ "fountain" ] )
        |> Dict.insert "26f3" ( "⛳", [ "golf" ] )
        |> Dict.insert "26f5" ( "⛵", [ "boat", "sailboat" ] )
        |> Dict.insert "26fa" ( "⛺", [ "tent" ] )
        |> Dict.insert "26fd" ( "⛽", [ "fuelpump" ] )
        |> Dict.insert "2702" ( "✂", [ "scissors" ] )
        |> Dict.insert "2705" ( "✅", [ "white_check_mark" ] )
        |> Dict.insert "2708" ( "✈", [ "airplane" ] )
        |> Dict.insert "2709" ( "✉", [ "email", "envelope" ] )
        |> Dict.insert "270a" ( "✊", [ "fist" ] )
        |> Dict.insert "270b" ( "✋", [ "hand", "raised_hand" ] )
        |> Dict.insert "270c" ( "✌", [ "v" ] )
        |> Dict.insert "270f" ( "✏", [ "pencil2" ] )
        |> Dict.insert "2712" ( "✒", [ "black_nib" ] )
        |> Dict.insert "2714" ( "✔", [ "heavy_check_mark" ] )
        |> Dict.insert "2716" ( "✖", [ "heavy_multiplication_x" ] )
        |> Dict.insert "2728" ( "✨", [ "sparkles" ] )
        |> Dict.insert "2733" ( "✳", [ "eight_spoked_asterisk" ] )
        |> Dict.insert "2734" ( "✴", [ "eight_pointed_black_star" ] )
        |> Dict.insert "2744" ( "❄", [ "snowflake" ] )
        |> Dict.insert "2747" ( "❇", [ "sparkle" ] )
        |> Dict.insert "274c" ( "❌", [ "x" ] )
        |> Dict.insert "274e" ( "❎", [ "negative_squared_cross_mark" ] )
        |> Dict.insert "2753" ( "❓", [ "question" ] )
        |> Dict.insert "2754" ( "❔", [ "grey_question" ] )
        |> Dict.insert "2755" ( "❕", [ "grey_exclamation" ] )
        |> Dict.insert "2757"
            ( "❗"
            , [ "exclamation"
              , "heavy_exclamation_mark"
              ]
            )
        |> Dict.insert "2764" ( "❤", [ "heart", "<3" ] )
        |> Dict.insert "2795" ( "➕", [ "heavy_plus_sign" ] )
        |> Dict.insert "2796" ( "➖", [ "heavy_minus_sign" ] )
        |> Dict.insert "2797" ( "➗", [ "heavy_division_sign" ] )
        |> Dict.insert "27a1" ( "➡", [ "arrow_right" ] )
        |> Dict.insert "27b0" ( "➰", [ "curly_loop" ] )
        |> Dict.insert "27bf" ( "➿", [ "loop" ] )
        |> Dict.insert "2934" ( "⤴", [ "arrow_heading_up" ] )
        |> Dict.insert "2935" ( "⤵", [ "arrow_heading_down" ] )
        |> Dict.insert "2b05" ( "⬅", [ "arrow_left" ] )
        |> Dict.insert "2b06" ( "⬆", [ "arrow_up" ] )
        |> Dict.insert "2b07" ( "⬇", [ "arrow_down" ] )
        |> Dict.insert "2b1b" ( "⬛", [ "black_large_square" ] )
        |> Dict.insert "2b1c" ( "⬜", [ "white_large_square" ] )
        |> Dict.insert "2b50" ( "⭐", [ "star" ] )
        |> Dict.insert "2b55" ( "⭕", [ "o" ] )
        |> Dict.insert "3030" ( "〰", [ "wavy_dash" ] )
        |> Dict.insert "303d" ( "〽", [ "part_alternation_mark" ] )
        |> Dict.insert "3297" ( "㊗", [ "congratulations" ] )
        |> Dict.insert "3299" ( "㊙", [ "secret" ] )
        |> Dict.insert "1f004" ( "\xD83C\xDC04", [ "mahjong" ] )
        |> Dict.insert "1f0cf" ( "\xD83C\xDCCF", [ "black_joker" ] )
        |> Dict.insert "1f170" ( "\xD83C\xDD70", [ "a" ] )
        |> Dict.insert "1f171" ( "\xD83C\xDD71", [ "b" ] )
        |> Dict.insert "1f17e" ( "\xD83C\xDD7E", [ "o2" ] )
        |> Dict.insert "1f17f" ( "\xD83C\xDD7F", [ "parking" ] )
        |> Dict.insert "1f18e" ( "\xD83C\xDD8E", [ "ab" ] )
        |> Dict.insert "1f191" ( "\xD83C\xDD91", [ "cl" ] )
        |> Dict.insert "1f192" ( "\xD83C\xDD92", [ "cool" ] )
        |> Dict.insert "1f193" ( "\xD83C\xDD93", [ "free" ] )
        |> Dict.insert "1f194" ( "\xD83C\xDD94", [ "id" ] )
        |> Dict.insert "1f195" ( "\xD83C\xDD95", [ "new" ] )
        |> Dict.insert "1f196" ( "\xD83C\xDD96", [ "ng" ] )
        |> Dict.insert "1f197" ( "\xD83C\xDD97", [ "ok" ] )
        |> Dict.insert "1f198" ( "\xD83C\xDD98", [ "sos" ] )
        |> Dict.insert "1f199" ( "\xD83C\xDD99", [ "up" ] )
        |> Dict.insert "1f19a" ( "\xD83C\xDD9A", [ "vs" ] )
        |> Dict.insert "1f201" ( "\xD83C\xDE01", [ "koko" ] )
        |> Dict.insert "1f202" ( "\xD83C\xDE02", [ "sa" ] )
        |> Dict.insert "1f21a" ( "\xD83C\xDE1A", [ "u7121" ] )
        |> Dict.insert "1f22f" ( "\xD83C\xDE2F", [ "u6307" ] )
        |> Dict.insert "1f232" ( "\xD83C\xDE32", [ "u7981" ] )
        |> Dict.insert "1f233" ( "\xD83C\xDE33", [ "u7a7a" ] )
        |> Dict.insert "1f234" ( "\xD83C\xDE34", [ "u5408" ] )
        |> Dict.insert "1f235" ( "\xD83C\xDE35", [ "u6e80" ] )
        |> Dict.insert "1f236" ( "\xD83C\xDE36", [ "u6709" ] )
        |> Dict.insert "1f237" ( "\xD83C\xDE37", [ "u6708" ] )
        |> Dict.insert "1f238" ( "\xD83C\xDE38", [ "u7533" ] )
        |> Dict.insert "1f239" ( "\xD83C\xDE39", [ "u5272" ] )
        |> Dict.insert "1f23a" ( "\xD83C\xDE3A", [ "u55b6" ] )
        |> Dict.insert "1f250" ( "\xD83C\xDE50", [ "ideograph_advantage" ] )
        |> Dict.insert "1f251" ( "\xD83C\xDE51", [ "accept" ] )
        |> Dict.insert "1f300" ( "\xD83C\xDF00", [ "cyclone" ] )
        |> Dict.insert "1f301" ( "\xD83C\xDF01", [ "foggy" ] )
        |> Dict.insert "1f302" ( "\xD83C\xDF02", [ "closed_umbrella" ] )
        |> Dict.insert "1f303" ( "\xD83C\xDF03", [ "night_with_stars" ] )
        |> Dict.insert "1f304" ( "\xD83C\xDF04", [ "sunrise_over_mountains" ] )
        |> Dict.insert "1f305" ( "\xD83C\xDF05", [ "sunrise" ] )
        |> Dict.insert "1f306" ( "\xD83C\xDF06", [ "city_sunset" ] )
        |> Dict.insert "1f307" ( "\xD83C\xDF07", [ "city_sunrise" ] )
        |> Dict.insert "1f308" ( "\xD83C\xDF08", [ "rainbow" ] )
        |> Dict.insert "1f309" ( "\xD83C\xDF09", [ "bridge_at_night" ] )
        |> Dict.insert "1f30a" ( "\xD83C\xDF0A", [ "ocean" ] )
        |> Dict.insert "1f30b" ( "\xD83C\xDF0B", [ "volcano" ] )
        |> Dict.insert "1f30c" ( "\xD83C\xDF0C", [ "milky_way" ] )
        |> Dict.insert "1f30d" ( "\xD83C\xDF0D", [ "earth_africa" ] )
        |> Dict.insert "1f30e" ( "\xD83C\xDF0E", [ "earth_americas" ] )
        |> Dict.insert "1f30f" ( "\xD83C\xDF0F", [ "earth_asia" ] )
        |> Dict.insert "1f310" ( "\xD83C\xDF10", [ "globe_with_meridians" ] )
        |> Dict.insert "1f311" ( "\xD83C\xDF11", [ "new_moon" ] )
        |> Dict.insert "1f312" ( "\xD83C\xDF12", [ "waxing_crescent_moon" ] )
        |> Dict.insert "1f313" ( "\xD83C\xDF13", [ "first_quarter_moon" ] )
        |> Dict.insert "1f314" ( "\xD83C\xDF14", [ "moon", "waxing_gibbous_moon" ] )
        |> Dict.insert "1f315" ( "\xD83C\xDF15", [ "full_moon" ] )
        |> Dict.insert "1f316" ( "\xD83C\xDF16", [ "waning_gibbous_moon" ] )
        |> Dict.insert "1f317" ( "\xD83C\xDF17", [ "last_quarter_moon" ] )
        |> Dict.insert "1f318" ( "\xD83C\xDF18", [ "waning_crescent_moon" ] )
        |> Dict.insert "1f319" ( "\xD83C\xDF19", [ "crescent_moon" ] )
        |> Dict.insert "1f320" ( "\xD83C\xDF20", [ "stars" ] )
        |> Dict.insert "1f31a" ( "\xD83C\xDF1A", [ "new_moon_with_face" ] )
        |> Dict.insert "1f31c" ( "\xD83C\xDF1C", [ "last_quarter_moon_with_face" ] )
        |> Dict.insert "1f31d" ( "\xD83C\xDF1D", [ "full_moon_with_face" ] )
        |> Dict.insert "1f31e" ( "\xD83C\xDF1E", [ "sun_with_face" ] )
        |> Dict.insert "1f31f" ( "\xD83C\xDF1F", [ "star2" ] )
        |> Dict.insert "1f330" ( "\xD83C\xDF30", [ "chestnut" ] )
        |> Dict.insert "1f331" ( "\xD83C\xDF31", [ "seedling" ] )
        |> Dict.insert "1f332" ( "\xD83C\xDF32", [ "evergreen_tree" ] )
        |> Dict.insert "1f333" ( "\xD83C\xDF33", [ "deciduous_tree" ] )
        |> Dict.insert "1f334" ( "\xD83C\xDF34", [ "palm_tree" ] )
        |> Dict.insert "1f335" ( "\xD83C\xDF35", [ "cactus" ] )
        |> Dict.insert "1f337" ( "\xD83C\xDF37", [ "tulip" ] )
        |> Dict.insert "1f338" ( "\xD83C\xDF38", [ "cherry_blossom" ] )
        |> Dict.insert "1f339" ( "\xD83C\xDF39", [ "rose" ] )
        |> Dict.insert "1f33a" ( "\xD83C\xDF3A", [ "hibiscus" ] )
        |> Dict.insert "1f33b" ( "\xD83C\xDF3B", [ "sunflower" ] )
        |> Dict.insert "1f33c" ( "\xD83C\xDF3C", [ "blossom" ] )
        |> Dict.insert "1f33d" ( "\xD83C\xDF3D", [ "corn" ] )
        |> Dict.insert "1f33e" ( "\xD83C\xDF3E", [ "ear_of_rice" ] )
        |> Dict.insert "1f33f" ( "\xD83C\xDF3F", [ "herb" ] )
        |> Dict.insert "1f340" ( "\xD83C\xDF40", [ "four_leaf_clover" ] )
        |> Dict.insert "1f341" ( "\xD83C\xDF41", [ "maple_leaf" ] )
        |> Dict.insert "1f342" ( "\xD83C\xDF42", [ "fallen_leaf" ] )
        |> Dict.insert "1f343" ( "\xD83C\xDF43", [ "leaves" ] )
        |> Dict.insert "1f344" ( "\xD83C\xDF44", [ "mushroom" ] )
        |> Dict.insert "1f345" ( "\xD83C\xDF45", [ "tomato" ] )
        |> Dict.insert "1f346" ( "\xD83C\xDF46", [ "eggplant" ] )
        |> Dict.insert "1f347" ( "\xD83C\xDF47", [ "grapes" ] )
        |> Dict.insert "1f348" ( "\xD83C\xDF48", [ "melon" ] )
        |> Dict.insert "1f349" ( "\xD83C\xDF49", [ "watermelon" ] )
        |> Dict.insert "1f34a" ( "\xD83C\xDF4A", [ "tangerine" ] )
        |> Dict.insert "1f34b" ( "\xD83C\xDF4B", [ "lemon" ] )
        |> Dict.insert "1f34c" ( "\xD83C\xDF4C", [ "banana" ] )
        |> Dict.insert "1f34d" ( "\xD83C\xDF4D", [ "pineapple" ] )
        |> Dict.insert "1f34e" ( "\xD83C\xDF4E", [ "apple" ] )
        |> Dict.insert "1f34f" ( "\xD83C\xDF4F", [ "green_apple" ] )
        |> Dict.insert "1f350" ( "\xD83C\xDF50", [ "pear" ] )
        |> Dict.insert "1f351" ( "\xD83C\xDF51", [ "peach" ] )
        |> Dict.insert "1f352" ( "\xD83C\xDF52", [ "cherries" ] )
        |> Dict.insert "1f353" ( "\xD83C\xDF53", [ "strawberry" ] )
        |> Dict.insert "1f354" ( "\xD83C\xDF54", [ "hamburger" ] )
        |> Dict.insert "1f355" ( "\xD83C\xDF55", [ "pizza" ] )
        |> Dict.insert "1f356" ( "\xD83C\xDF56", [ "meat_on_bone" ] )
        |> Dict.insert "1f357" ( "\xD83C\xDF57", [ "poultry_leg" ] )
        |> Dict.insert "1f358" ( "\xD83C\xDF58", [ "rice_cracker" ] )
        |> Dict.insert "1f359" ( "\xD83C\xDF59", [ "rice_ball" ] )
        |> Dict.insert "1f35a" ( "\xD83C\xDF5A", [ "rice" ] )
        |> Dict.insert "1f35b" ( "\xD83C\xDF5B", [ "curry" ] )
        |> Dict.insert "1f35c" ( "\xD83C\xDF5C", [ "ramen" ] )
        |> Dict.insert "1f35d" ( "\xD83C\xDF5D", [ "spaghetti" ] )
        |> Dict.insert "1f35e" ( "\xD83C\xDF5E", [ "bread" ] )
        |> Dict.insert "1f35f" ( "\xD83C\xDF5F", [ "fries" ] )
        |> Dict.insert "1f360" ( "\xD83C\xDF60", [ "sweet_potato" ] )
        |> Dict.insert "1f361" ( "\xD83C\xDF61", [ "dango" ] )
        |> Dict.insert "1f362" ( "\xD83C\xDF62", [ "oden" ] )
        |> Dict.insert "1f363" ( "\xD83C\xDF63", [ "sushi" ] )
        |> Dict.insert "1f364" ( "\xD83C\xDF64", [ "fried_shrimp" ] )
        |> Dict.insert "1f365" ( "\xD83C\xDF65", [ "fish_cake" ] )
        |> Dict.insert "1f366" ( "\xD83C\xDF66", [ "icecream" ] )
        |> Dict.insert "1f367" ( "\xD83C\xDF67", [ "shaved_ice" ] )
        |> Dict.insert "1f368" ( "\xD83C\xDF68", [ "ice_cream" ] )
        |> Dict.insert "1f369" ( "\xD83C\xDF69", [ "doughnut" ] )
        |> Dict.insert "1f36a" ( "\xD83C\xDF6A", [ "cookie" ] )
        |> Dict.insert "1f36b" ( "\xD83C\xDF6B", [ "chocolate_bar" ] )
        |> Dict.insert "1f36c" ( "\xD83C\xDF6C", [ "candy" ] )
        |> Dict.insert "1f36d" ( "\xD83C\xDF6D", [ "lollipop" ] )
        |> Dict.insert "1f36e" ( "\xD83C\xDF6E", [ "custard" ] )
        |> Dict.insert "1f36f" ( "\xD83C\xDF6F", [ "honey_pot" ] )
        |> Dict.insert "1f370" ( "\xD83C\xDF70", [ "cake" ] )
        |> Dict.insert "1f371" ( "\xD83C\xDF71", [ "bento" ] )
        |> Dict.insert "1f372" ( "\xD83C\xDF72", [ "stew" ] )
        |> Dict.insert "1f373" ( "\xD83C\xDF73", [ "egg" ] )
        |> Dict.insert "1f374" ( "\xD83C\xDF74", [ "fork_and_knife" ] )
        |> Dict.insert "1f375" ( "\xD83C\xDF75", [ "tea" ] )
        |> Dict.insert "1f376" ( "\xD83C\xDF76", [ "sake" ] )
        |> Dict.insert "1f377" ( "\xD83C\xDF77", [ "wine_glass" ] )
        |> Dict.insert "1f378" ( "\xD83C\xDF78", [ "cocktail" ] )
        |> Dict.insert "1f379" ( "\xD83C\xDF79", [ "tropical_drink" ] )
        |> Dict.insert "1f37a" ( "\xD83C\xDF7A", [ "beer" ] )
        |> Dict.insert "1f37b" ( "\xD83C\xDF7B", [ "beers" ] )
        |> Dict.insert "1f37c" ( "\xD83C\xDF7C", [ "baby_bottle" ] )
        |> Dict.insert "1f380" ( "\xD83C\xDF80", [ "ribbon" ] )
